const A="https://api.open-meteo.com/v1/forecast";
const cities=[
 ["Goa","Beaches & sunshine","🏝️",15.2993,74.1240],["Jaipur","Royal Rajasthan","🏰",26.9124,75.7873],
 ["Manali","Mountains & snow","🏔️",32.2396,77.1887],["Kerala","Backwaters","🌴",9.9312,76.2673],["Kashmir","Paradise","🏞️",34.0837,74.7973]
];
const tools=[
 ["price","📉","Price alerts","Track fare changes"],["weather","☀️","Live weather","Real-time forecast"],["nearby","📍","Nearby places","Find around you"],["currency","💱","Currency","Quick conversion"],
 ["offers","🎁","Offers","Deals & coupons"],["wallet","💳","Wallet","Manage travel budget"],["saved","♡","Saved","Your favourites"],["alerts","🔔","Alerts","Travel notifications"],
 ["support","🎧","Support","Help center"],["planner","🗺️","Trip planner","Build itinerary"],["checklist","☑️","Checklist","Travel checklist"],["visa","🛂","Visa guide","Destination basics"],
 ["insurance","🛡️","Insurance","Travel protection"],["airport","🛫","Airport info","Terminal essentials"],["trainstatus","🚆","Train status","Check your train"],["pnr","🎫","PNR status","Demo PNR checker"],
 ["buslive","🚌","Bus tracker","Demo tracking"],["cab","🚕","Cab estimate","Fare estimator"],["hotelmap","🏨","Hotel map","Stay discovery"],["flights","✈️","Flight tracker","Demo flight status"]
];
let mode="flights",last=[];

function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function renderSearch(){
 let f=document.getElementById("searchFields"),d=today();
 if(mode==="hotels") f.innerHTML=`<div class="search-fields">${field("Destination","", "City / hotel / area")}${field("Check-in",d)}${field("Check-out",d)}${field("Guests","2 Guests, 1 Room")}</div>`;
 else if(mode==="cabs") f.innerHTML=`<div class="search-fields">${field("Pickup","", "Current location")}${field("Drop","", "Destination")}${field("Date",d)}${field("Time","10:00")}</div>`;
 else f.innerHTML=`<div class="search-fields">${field("From","","City / airport")}${field("To","","City / airport")}${field("Departure",d)}${field("Travellers","1 Traveller")}</div>`;
}
function field(label,value="",ph=""){return `<label class="field"><small>${label}</small><input value="${esc(value)}" placeholder="${ph}" ${label==="Departure"||label==="Check-in"||label==="Check-out"||label==="Date"?'type="date"':label==="Time"?'type="time"':''}></label>`}
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".bottomnav button").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));window.scrollTo(0,0);if(id==="bookings")renderBookings()}
function toast(m){let t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function openFeature(type){
 showScreen("feature");const titles={price:["Price Alerts","Get notified when fares change"],weather:["Live Weather","Real-time weather data"],nearby:["Nearby Places","Discover useful places around you"],currency:["Currency Converter","Quick conversion"],offers:["Offers & Rewards","Travel deals"],wallet:["Tripora Wallet","Plan and track your travel budget"],saved:["Saved Places","Your favourite destinations"],alerts:["Alerts","Travel notifications"],support:["Help & Support","We're here to help"],planner:["Trip Planner","Build a simple itinerary"],checklist:["Travel Checklist","Don't forget the essentials"],visa:["Visa Guide","Basic destination travel information"],insurance:["Travel Protection","Insurance planning"],airport:["Airport Info","Quick airport essentials"],trainstatus:["Train Status","Demo live-status interface"],pnr:["PNR Status","Enter a PNR to check"],buslive:["Bus Tracker","Demo live bus tracking"],cab:["Cab Fare Estimate","Estimate your ride"],hotelmap:["Hotel Discovery","Popular stays"],flights:["Flight Tracker","Demo flight status"]};document.getElementById("featureTitle").textContent=titles[type]?.[0]||"Travel Tool";document.getElementById("featureSub").textContent=titles[type]?.[1]||"Useful travel utility";
 let b=document.getElementById("featureBody");
 if(type==="weather") b.innerHTML=`<div class="info-card"><h2>Live weather</h2><p class="muted">Powered by Open-Meteo — no API key required.</p><select id="weatherCity">${cities.map((c,i)=>`<option value="${i}">${c[0]}</option>`).join("")}</select><button class="full" style="margin-top:12px" onclick="weather()">Get live weather</button><div id="weatherOut"></div></div>`;
 else if(type==="currency") b.innerHTML=`<div class="info-card"><h2>Currency converter</h2><p class="muted">Uses live rates when the public endpoint is available.</p><input id="amount" placeholder="Amount" type="number" value="100"><div class="search-fields"><select id="from"><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option></select><select id="to"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></div><button class="full" onclick="convert()">Convert</button><div id="currencyOut"></div></div>`;
 else if(type==="cab") b.innerHTML=`<div class="info-card"><h2>Cab fare estimator</h2><input id="km" type="number" value="10" placeholder="Distance in km"><select id="cabtype"><option value="18">Mini — ₹18/km</option><option value="24">Sedan — ₹24/km</option><option value="32">SUV — ₹32/km</option></select><button class="full" onclick="estimate()">Estimate fare</button><h2 id="fare"></h2></div>`;
 else if(type==="planner") b.innerHTML=`<div class="info-card"><h2>Build your trip</h2><input id="planCity" placeholder="Destination"><input id="planDays" type="number" value="3" placeholder="Days"><button class="full" onclick="makePlan()">Create itinerary</button><div id="planOut"></div></div>`;
 else if(type==="checklist") b.innerHTML=`<div class="info-card"><h2>Travel checklist</h2>${["ID / passport","Tickets & hotel confirmation","Phone + charger","Medicine","Cash / cards","Clothes","Toiletries","Emergency contacts"].map(x=>`<label style="display:block;padding:11px 0"><input type="checkbox"> ${x}</label>`).join("")}</div>`;
 else if(type==="pnr") b.innerHTML=`<div class="info-card"><h2>PNR status</h2><input id="pnrInput" maxlength="10" placeholder="Enter 10 digit PNR"><button class="full" onclick="checkPNR()">Check status</button><div id="pnrOut"></div></div>`;
 else if(type==="trainstatus"||type==="flights"||type==="buslive") b.innerHTML=`<div class="info-card"><h2>Live-status interface</h2><p>Enter your service number to check status.</p><input id="serviceNo" placeholder="Service / flight / train number"><button class="full" onclick="demoStatus()">Check status</button><div id="statusOut"></div></div>`;
 else if(type==="nearby") b.innerHTML=`<div class="info-card"><h2>Nearby</h2><p>Location permission can be used to find travel essentials.</p><button class="full" onclick="nearby()">Use my location</button><div id="nearOut"></div></div>`;
 else if(type==="saved") b.innerHTML=`<div id="savedOut"></div>`;
 else if(type==="wallet") b.innerHTML=`<div class="info-card"><h2>Travel budget</h2><input id="budget" type="number" value="10000" placeholder="Total budget"><input id="spent" type="number" value="2500" placeholder="Spent"><button class="full" onclick="wallet()">Calculate remaining</button><div id="walletOut"></div></div>`;
 else b.innerHTML=`<div class="info-card"><h2>${titles[type]?.[0]||"Coming tools"}</h2><p>This module is fully interactive in demo mode and is ready to connect to Firebase / provider APIs.</p><button class="full" onclick="toast('Saved successfully')">Continue</button></div>`;
 if(type==="saved") renderSaved();
}
async function weather(){let c=cities[+document.getElementById("weatherCity").value];try{let r=await fetch(`${A}?latitude=${c[3]}&longitude=${c[4]}&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code&timezone=auto`);let d=await r.json();document.getElementById("weatherOut").innerHTML=`<div class="info-card"><h2>${c[2]} ${c[0]} · ${Math.round(d.current.temperature_2m)}°C</h2><p>Humidity ${d.current.relative_humidity_2m}% · Wind ${d.current.wind_speed_10m} km/h</p><small>Live data: Open-Meteo</small></div>`}catch(e){toast("Weather service unavailable")}}
async function convert(){let a=+document.getElementById("amount").value||0,f=document.getElementById("from").value,t=document.getElementById("to").value;try{let r=await fetch(`https://api.frankfurter.app/latest?amount=${a}&from=${f}&to=${t}`);let d=await r.json();document.getElementById("currencyOut").innerHTML=`<div class="info-card"><h2>${a} ${f} = ${d.rates[t]} ${t}</h2><small>Live public exchange-rate endpoint</small></div>`}catch(e){toast("Rate service unavailable")}}
function estimate(){let km=+document.getElementById("km").value||0,rate=+document.getElementById("cabtype").value;document.getElementById("fare").textContent="Estimated fare: ₹"+Math.max(99,Math.round(km*rate)).toLocaleString("en-IN")}
function wallet(){let b=+document.getElementById("budget").value||0,s=+document.getElementById("spent").value||0;document.getElementById("walletOut").innerHTML=`<div class="info-card"><h2>₹${Math.max(0,b-s).toLocaleString("en-IN")} remaining</h2><p>Used ₹${s.toLocaleString("en-IN")} of ₹${b.toLocaleString("en-IN")}</p></div>`}
function makePlan(){let c=document.getElementById("planCity").value||"your destination",d=Math.max(1,+document.getElementById("planDays").value||3);document.getElementById("planOut").innerHTML=`<div class="info-card"><h3>${esc(c)} — ${d} days</h3>${Array.from({length:d},(_,i)=>`<p><b>Day ${i+1}:</b> Morning sightseeing · Local lunch · Evening exploration</p>`).join("")}</div>`}
function checkPNR(){let p=document.getElementById("pnrInput").value;document.getElementById("pnrOut").innerHTML=`<div class="info-card"><h3>Demo result</h3><p>PNR ${esc(p||"—")} · Status: <b>Confirmed / RAC preview</b></p><small>Connect IRCTC/provider API for production status.</small></div>`}
function demoStatus(){document.getElementById("statusOut").innerHTML=`<div class="info-card"><h3>On schedule</h3><p>Service ${esc(document.getElementById("serviceNo").value||"—")} · Next update in 5 min.</p></div>`}
function nearby(){if(!navigator.geolocation)return toast("Location not supported");navigator.geolocation.getCurrentPosition(p=>document.getElementById("nearOut").innerHTML=`<div class="info-card"><h3>Location ready 📍</h3><p>Latitude ${p.coords.latitude.toFixed(4)} · Longitude ${p.coords.longitude.toFixed(4)}</p><small>Use a maps/places API to show nearby businesses.</small></div>`,()=>toast("Location permission denied"))}
function renderSaved(){let s=JSON.parse(localStorage.getItem("saved")||"[]");document.getElementById("savedOut").innerHTML=s.length?s.map(x=>`<div class="trip-card"><h3>${esc(x)}</h3><button class="book" onclick="savePlace('${esc(x)}')">Remove</button></div>`).join(""):`<div class="info-card"><h3>No saved places</h3><p>Save a destination from Discover.</p></div>`}
function savePlace(x){let s=JSON.parse(localStorage.getItem("saved")||"[]");s=s.includes(x)?s.filter(a=>a!==x):[...s,x];localStorage.setItem("saved",JSON.stringify(s));toast("Saved places updated")}
function renderDest(){document.getElementById("destinations").innerHTML=cities.map(c=>`<div class="destination" onclick="destination('${c[0]}')"><div><div style="font-size:30px">${c[2]}</div><b>${c[0]}</b><small>${c[1]}</small></div></div>`).join("");document.getElementById("discoverGrid").innerHTML=cities.map(c=>`<div class="discover-card"><div class="discover-img">${c[2]}</div><div><h3>${c[0]}</h3><p>${c[1]}</p><button class="book" onclick="savePlace('${c[0]}')">♡ Save</button></div></div>`).join("")}
function renderTools(){document.getElementById("featureGrid").innerHTML=tools.slice(0,12).map(t=>`<button class="tool" onclick="openFeature('${t[0]}')"><span>${t[1]}</span><b>${t[2]}</b><small>${t[3]}</small></button>`).join("")}
function destination(c){setMode("flights");toast("Searching options to "+c);setTimeout(search,300)}
function setMode(m){mode=m;document.querySelectorAll(".search-tabs button").forEach(x=>x.classList.toggle("sel",x.dataset.type===m));renderSearch()}
function search(){last=makeResults(mode);showScreen("results");document.getElementById("resultTitle").textContent=mode[0].toUpperCase()+mode.slice(1);document.getElementById("resultSub").textContent=last.length+" options found";document.getElementById("resultsList").innerHTML=last.map((r,i)=>`<div class="result-card"><div><h3>${r[0]}</h3><div class="muted">${r[1]}</div><div class="muted">${r[2]} · ${r[3]}</div></div><div class="result-price">${r[4]}<br><button class="book" onclick="book(${i})">Book</button></div></div>`).join("")}
function makeResults(m){let d={flights:[["IndiGo","Delhi → Mumbai","06:10–08:20","Non-stop","₹3,499"],["Air India","Delhi → Mumbai","10:35–12:50","Non-stop","₹4,120"],["Akasa Air","Delhi → Goa","18:15–20:55","Non-stop","₹4,299"]],hotels:[["The Fern","Goa","4.5 ★","Breakfast","₹2,899"],["Royal Palace","Jaipur","4.3 ★","Free cancellation","₹2,199"],["Mountain View","Manali","4.7 ★","Breakfast","₹3,499"]],trains:[["Rajdhani Express","Delhi → Mumbai","16:55–08:35","2A / 3A","₹2,095"],["Vande Bharat","Delhi → Varanasi","06:00–14:00","CC / EC","₹1,795"],["Shatabdi","Delhi → Jaipur","06:10–10:40","CC","₹850"]],buses:[["IntrCity","Delhi → Jaipur","22:30–04:15","AC Sleeper","₹699"],["ZingBus","Delhi → Chandigarh","23:00–04:45","AC Sleeper","₹599"],["UPSRTC","Delhi → Agra","07:30–11:00","AC Seater","₹399"]],cabs:[["City Sedan","Delhi → Airport","Now","4 seats","₹699"],["Premium SUV","Delhi → Agra","Today","6 seats","₹3,499"],["Hatchback","Delhi local","Now","4 seats","₹449"]]} ;return d[m]}
function book(i){let r=last[i],b=JSON.parse(localStorage.getItem("bookings")||"[]");b.push({mode,name:r[0],route:r[1],time:r[2],price:r[4],id:"TRP"+Date.now().toString().slice(-7)});localStorage.setItem("bookings",JSON.stringify(b));toast("Booking confirmed");showScreen("bookings")}
function renderBookings(){let b=JSON.parse(localStorage.getItem("bookings")||"[]");document.getElementById("bookingList").innerHTML=b.length?b.slice().reverse().map(x=>`<div class="trip-card"><span class="muted">${x.mode.toUpperCase()} · CONFIRMED</span><h3>${esc(x.name)}</h3><p>${esc(x.route)} · ${esc(x.time)}</p><b>${x.price}</b><small style="display:block;margin-top:7px;color:#7b8492">Tripora ID: ${x.id}</small></div>`).join(""):`<div class="info-card" style="text-align:center;padding:50px"><div style="font-size:45px">🧳</div><h2>No trips yet</h2><p>Book a flight, hotel, train, bus or cab and it appears here.</p><button class="full" onclick="showScreen('home')">Explore travel</button></div>`}
function renderOffers(){document.getElementById("offersList").innerHTML=[["✈️","FLIGHT SALE","Domestic fares from ₹1,999"],["🏨","HOTEL WEEK","Up to 35% off selected stays"],["🚌","BUS BONANZA","Save extra ₹500"],["🎁","NEW USER","Special welcome rewards"]].map(x=>`<div class="offer-card"><div><small>${x[1]}</small><h2>${x[2]}</h2><p class="muted">Limited-time Tripora offer.</p></div><span style="font-size:45px">${x[0]}</span></div>`).join("")}
function openLogin(){document.getElementById("modalBody").innerHTML=`<h2>Welcome to Tripora</h2><p class="muted">Demo account now. Firebase Auth can replace this flow.</p><input id="loginName" placeholder="Your name"><input id="loginEmail" type="email" placeholder="Email address"><button class="full" onclick="login()">Continue</button>`;document.getElementById("modal").classList.remove("hidden")}
function login(){let n=document.getElementById("loginName").value||"Traveller",e=document.getElementById("loginEmail").value||"Demo account";localStorage.setItem("user",JSON.stringify({n,e}));document.getElementById("profileName").textContent=n;document.getElementById("profileEmail").textContent=e;document.getElementById("avatar").textContent=n[0].toUpperCase();closeModal();toast("Welcome, "+n+"!")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function toggleDark(){document.body.classList.toggle("dark");localStorage.setItem("dark",document.body.classList.contains("dark"))}
function closeDrawer(){document.getElementById("drawer").classList.remove("open")}
function setup(){renderDest();renderTools();renderSearch();renderOffers();document.querySelectorAll(".search-tabs button").forEach(x=>x.onclick=()=>setMode(x.dataset.type));document.getElementById("searchBtn").onclick=search;document.getElementById("menuBtn").onclick=()=>document.getElementById("drawer").classList.add("open");document.getElementById("bellBtn").onclick=()=>openFeature("alerts");document.querySelectorAll(".bottomnav button").forEach(x=>x.onclick=()=>showScreen(x.dataset.screen));let u=JSON.parse(localStorage.getItem("user")||"null");if(u){profileName.textContent=u.n;profileEmail.textContent=u.e;avatar.textContent=u.n[0].toUpperCase()}if(localStorage.getItem("dark")==="true")toggleDark()}
setup();

if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(()=>{})}
